Mostly integrated ruby build environment. TODO: Support automatic disabling of ruby if not found.
git-svn-id: svn://red.pomac.com/rage@136 55c13d69-e7e2-0310-b639-a4a306287c42

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP CCAS CCASFLAGS build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE ALLOCA GLIBC21 LIBICONV LTLIBICONV INTLBISON BUILD_INCLUDED_LIBINTL USE_INCLUDED_LIBINTL CATOBJEXT DATADIRNAME INSTOBJEXT GENCAT INTLOBJS INTL_LIBTOOL_SUFFIX_PREFIX INTLLIBS LIBINTL LTLIBINTL POSUB sedpath unamepath PKG_CONFIG GLIB_CFLAGS GLIB_LIBS GLIB_GENMARSHAL GOBJECT_QUERY GLIB_MKENUMS GTK_CFLAGS GTK_LIBS pkgconfigpath perlpath pythonpath USE_OPENSSL_TRUE USE_OPENSSL_FALSE DO_TEXT_TRUE DO_TEXT_FALSE DO_GTK_TRUE DO_GTK_FALSE DO_PERL_TRUE DO_PERL_FALSE DO_PYTHON_TRUE DO_PYTHON_FALSE DO_TCL_TRUE DO_TCL_FALSE DO_PLUGIN_TRUE DO_PLUGIN_FALSE USE_MMX_TRUE USE_MMX_FALSE gdkpixbufcsourcepath GUI_LIBS GUI_CFLAGS COMMON_LIBS COMMON_CFLAGS PERL_CFLAGS PERL_LDFLAGS PY_CFLAGS PY_LIBS TCL_LIBS TCL_CFLAGS ragelibdir ragesharedir PLUGIN_INCLUDES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP CCAS CCASFLAGS build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE ALLOCA GLIBC21 LIBICONV LTLIBICONV INTLBISON BUILD_INCLUDED_LIBINTL USE_INCLUDED_LIBINTL CATOBJEXT DATADIRNAME INSTOBJEXT GENCAT INTLOBJS INTL_LIBTOOL_SUFFIX_PREFIX INTLLIBS LIBINTL LTLIBINTL POSUB sedpath unamepath PKG_CONFIG GLIB_CFLAGS GLIB_LIBS GLIB_GENMARSHAL GOBJECT_QUERY GLIB_MKENUMS GTK_CFLAGS GTK_LIBS pkgconfigpath perlpath pythonpath USE_OPENSSL_TRUE USE_OPENSSL_FALSE DO_TEXT_TRUE DO_TEXT_FALSE DO_GTK_TRUE DO_GTK_FALSE DO_PERL_TRUE DO_PERL_FALSE DO_PYTHON_TRUE DO_PYTHON_FALSE DO_RUBY_TRUE DO_RUBY_FALSE DO_TCL_TRUE DO_TCL_FALSE DO_PLUGIN_TRUE DO_PLUGIN_FALSE USE_MMX_TRUE USE_MMX_FALSE gdkpixbufcsourcepath GUI_LIBS GUI_CFLAGS COMMON_LIBS COMMON_CFLAGS PERL_CFLAGS PERL_LDFLAGS PY_CFLAGS PY_LIBS TCL_LIBS TCL_CFLAGS ragelibdir ragesharedir PLUGIN_INCLUDES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1056,6 +1056,7 @@ Optional Features:
   --disable-perl          don't build the perl plugin
   --disable-perl_old      no backwards compatibility for perl plugin
   --enable-tcl=PATH       directory with Tcl config file: tclConfig.sh
+  --disable-ruby        don't build the ruby plugin
   --disable-plugin        disable plugin support
   --disable-mmx           disable MMX assembly routines
   --enable-shm            enable use of XShm for fast tinting (default: no)
@@ -3937,7 +3938,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3940 "configure"' > conftest.$ac_ext
+  echo '#line 3941 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5293,7 +5294,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5296:" \
+echo "$as_me:5297:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6327,11 +6328,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6330: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6331: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6334: \$? = $ac_status" >&5
+   echo "$as_me:6335: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6560,11 +6561,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6563: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6564: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6567: \$? = $ac_status" >&5
+   echo "$as_me:6568: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6620,11 +6621,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6623: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6624: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6627: \$? = $ac_status" >&5
+   echo "$as_me:6628: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7999,7 +8000,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 8002 "configure"' > conftest.$ac_ext
+    echo '#line 8003 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8859,7 +8860,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8862 "configure"
+#line 8863 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8957,7 +8958,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8960 "configure"
+#line 8961 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11136,11 +11137,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11139: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11140: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11143: \$? = $ac_status" >&5
+   echo "$as_me:11144: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11196,11 +11197,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11199: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11200: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11203: \$? = $ac_status" >&5
+   echo "$as_me:11204: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11752,7 +11753,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 11755 "configure"' > conftest.$ac_ext
+    echo '#line 11756 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -12612,7 +12613,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12615 "configure"
+#line 12616 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12710,7 +12711,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12713 "configure"
+#line 12714 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13537,11 +13538,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13540: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13541: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13544: \$? = $ac_status" >&5
+   echo "$as_me:13545: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13597,11 +13598,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13600: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13601: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13604: \$? = $ac_status" >&5
+   echo "$as_me:13605: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14956,7 +14957,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 14959 "configure"' > conftest.$ac_ext
+    echo '#line 14960 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15686,11 +15687,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15689: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15690: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15693: \$? = $ac_status" >&5
+   echo "$as_me:15694: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15919,11 +15920,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15922: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15923: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15926: \$? = $ac_status" >&5
+   echo "$as_me:15927: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15979,11 +15980,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15982: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15983: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15986: \$? = $ac_status" >&5
+   echo "$as_me:15987: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17358,7 +17359,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 17361 "configure"' > conftest.$ac_ext
+    echo '#line 17362 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18218,7 +18219,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18221 "configure"
+#line 18222 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18316,7 +18317,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18319 "configure"
+#line 18320 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23719,6 +23720,14 @@ else
   tcl=yes
 fi;
 
+# Check whether --enable-ruby or --disable-ruby was given.
+if test "${enable_ruby+set}" = set; then
+  enableval="$enable_ruby"
+  ruby=$enableval
+else
+  ruby=yes
+fi;
+
 # Check whether --enable-plugin or --disable-plugin was given.
 if test "${enable_plugin+set}" = set; then
   enableval="$enable_plugin"
@@ -26197,6 +26206,16 @@ fi
 
 
 
+if test "x$ruby" = "xyes"; then
+  DO_RUBY_TRUE=
+  DO_RUBY_FALSE='#'
+else
+  DO_RUBY_TRUE='#'
+  DO_RUBY_FALSE=
+fi
+
+
+
 if test "x$tcl" = "xyes"; then
   DO_TCL_TRUE=
   DO_TCL_FALSE='#'
@@ -27942,7 +27961,7 @@ _ACEOF
 
 fi
 
-                                                                                                                        ac_config_files="$ac_config_files Makefile src/Makefile src/common/Makefile src/fe-text/Makefile src/fe-gtk/Makefile src/pixmaps/Makefile plugins/Makefile plugins/python/Makefile plugins/perl/Makefile plugins/tcl/Makefile intl/Makefile po/Makefile.in"
+                                                                                                                                  ac_config_files="$ac_config_files Makefile src/Makefile src/common/Makefile src/fe-text/Makefile src/fe-gtk/Makefile src/pixmaps/Makefile plugins/Makefile plugins/python/Makefile plugins/perl/Makefile plugins/tcl/Makefile plugins/ruby/Makefile intl/Makefile po/Makefile.in"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -28094,6 +28113,13 @@ if test -z "${DO_PYTHON_TRUE}" && test -z "${DO_PYTHON_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"DO_PYTHON\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"DO_PYTHON\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${DO_RUBY_TRUE}" && test -z "${DO_RUBY_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"DO_RUBY\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"DO_RUBY\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -28579,6 +28605,7 @@ do
   "plugins/python/Makefile" ) CONFIG_FILES="$CONFIG_FILES plugins/python/Makefile" ;;
   "plugins/perl/Makefile" ) CONFIG_FILES="$CONFIG_FILES plugins/perl/Makefile" ;;
   "plugins/tcl/Makefile" ) CONFIG_FILES="$CONFIG_FILES plugins/tcl/Makefile" ;;
+  "plugins/ruby/Makefile" ) CONFIG_FILES="$CONFIG_FILES plugins/ruby/Makefile" ;;
   "intl/Makefile" ) CONFIG_FILES="$CONFIG_FILES intl/Makefile" ;;
   "po/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES po/Makefile.in" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
@@ -28783,6 +28810,8 @@ s,@DO_PERL_TRUE@,$DO_PERL_TRUE,;t t
 s,@DO_PERL_FALSE@,$DO_PERL_FALSE,;t t
 s,@DO_PYTHON_TRUE@,$DO_PYTHON_TRUE,;t t
 s,@DO_PYTHON_FALSE@,$DO_PYTHON_FALSE,;t t
+s,@DO_RUBY_TRUE@,$DO_RUBY_TRUE,;t t
+s,@DO_RUBY_FALSE@,$DO_RUBY_FALSE,;t t
 s,@DO_TCL_TRUE@,$DO_TCL_TRUE,;t t
 s,@DO_TCL_FALSE@,$DO_TCL_FALSE,;t t
 s,@DO_PLUGIN_TRUE@,$DO_PLUGIN_TRUE,;t t
@@ -29634,7 +29663,7 @@ echo
 echo Building GTK+ Interface .... : $gtkfe
 echo Building TEXT Interface .... : $textfe
 echo
-echo PLUGINS: Perl: $perl Python: $python TCL: $tcl
+echo PLUGINS: Perl: $perl Python: $python TCL: $tcl Ruby: $ruby
 echo
 echo mmx tinting ......... : $mmx
 echo XShm tinting ........ : $shm\	plugin interface .... : $plugin
